### ISSUE TITLE
unable to install because homebrew removed python@2

### ISSUE THREAD

**Issue by pauliuslukosiunas** [EugenMayer/homebrew-dockersync#12]
unable to install eugenmayer/dockersync/unison because homebrew removed python@2 from 2020-01-01.

==> Installing unox from eugenmayer/dockersync
Error: No available formula with the name "python@2" (dependency of eugenmayer/dockersync/unox)
==> Searching for a previously deleted formula (in the last month)...
python@2 was deleted from homebrew/core in commit 028f11f9e4:
  python@2: delete (https://github.com/Homebrew/homebrew-core/issues/49796)
  EOL 1 January 2020.
  We gave it 1 month more to live so that people had time to migrate.
  All in all, developers had 11 years to do their migration.
  You can use the `brew extract` command and maintain python@2 in your own
  tap if necessary:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 028f11f9e4^:Formula/python@2.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by EugenMayer** [comment]
fixed by #11
