### ISSUE TITLE
Brew install fails due to "recognised Python dependency could not be found"

### ISSUE THREAD

**Issue by petetnt** [EugenMayer/homebrew-dockersync#14]
Steps to repro:

1. `brew update`
2. `brew install eugenmayer/dockersync/unox`

Expected:

Install succeeds

Actual:

```
Error: An exception occurred within a child process:
  FormulaUnknownPythonError: The version of Python to use with the virtualenv in the `eugenmayer/dockersync/unox` formula
cannot be guessed automatically because a recognised Python dependency could not be found.

If you are using a non-standard Python depedency, please add `:using => "python@x.y"` to
`virtualenv_install_with_resources` to resolve the issue manually.
```

The check was added in https://github.com/Homebrew/brew/pull/7959 and I think the root cause is https://github.com/EugenMayer/homebrew-dockersync/pull/11

Updating the formula to include `virtualenv_install_with_resources(:using => "python@3")` fixed the issue locally for me.

**Comment by ziaulrehman40** [comment]
Same issue, any more instructions to fix it temporarily would be great. Thanks.

**Comment by petetnt** [comment]
@ziaulrehman40 I copied the formula to `/tmp/unox.rb`, made the fix and installed it with `brew install /tmp/unox.rb`

Here's the updated formula from #15, notice the `virtualenv_install_with_resources(:using => "python@3")` line. Just copy that to somewhere and install it :)

https://raw.githubusercontent.com/EugenMayer/homebrew-dockersync/238028f2e2ae028cbfb8f5814d887ad2e80376fe/Formula/unox.rb

**Comment by gustavosolomon** [comment]
@petetnt I have installed unox sucessfully with this method, but "docker-sync" still not an executable.

Can you help me? Thanks

**Comment by skoskie** [comment]
@gustavosolomon I'll assume you have Ruby installed already? In terminal type `gem environment` and it should give you a bunch of helpful info. Check your `GEM_PATHS` value and make sure that directory is in your `$PATH`.

**Comment by petetnt** [comment]
@gustavosolomon yep, like skoskie mentions the `GEM_PATHS` is probably not in your `PATH`. If you are using `rmv`, try `source ~/.rvm/scripts/rvm`

**Comment by gustavosolomon** [comment]
@skoskie @petetnt thanks! but which of the 3 paths should I include in `$PATH`?

```
- /Library/Ruby/Gems/2.6.0
- /Users/XXX/.gem/ruby/2.6.0
- /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
```

PS: both `gem` (v3.0.3) and `ruby` (v2.6.3p62) are already installed.

**Comment by petetnt** [comment]
I think the gem is probably under `/Users/XXX/.gem/ruby/2.6.0`, but you could try doing `ls /Users/XXX/.gem/ruby/2.6.0` and checking that the `docker-sync` bin is there (or a symlink to it) :)

**Comment by gustavosolomon** [comment]
I've made it. Just uninstalled `unison` and `unox` and installed through `sudo gem install docker-sync`. 😎

**Comment by ls-sam-leatherdale** [comment]
> I've made it. Just uninstalled `unison` and `unox` and installed through `sudo gem install docker-sync`. 😎

That only works if you are using the `native_osx` sync strategy, not the `unison` sync strategy.

For those of us who need the `unison` sync strategy, the Python dependency that the `unox` formula relies on needs to be fixed.

**Comment by EugenMayer** [comment]
@saml-kounta are we considering #15  to be a fix for this issue? Seems most of the people are going well with this fix. 

Any concerns?

**Comment by ls-sam-leatherdale** [comment]
@EugenMayer Thanks for getting back to me.

The changes in that PR certainly fix the issue, I just don't know enough about Homebrew to what the difference is between doing what the PR does, or changing the version of python that the formula depends on to be a newer version, that Homebrew currently distributes.

**Comment by EugenMayer** [comment]
This is my only tap, thus my experience is fairlz limuted, when it comes to authoring homebrew taps
