### ISSUE TITLE
Error while install with brew

### ISSUE THREAD

**Issue by arioch1984** [EugenMayer/homebrew-dockersync#5]
Hi...

...Thank's for your work!

I followed your instructions for installing via homebrew, but when I call brew install I have this error:
`MacBook-Pro-di-Fabio-2:~ fabiobrunelli$ brew install eugenmayer/dockersync/unox
==> Installing unox from eugenmayer/dockersync
==> Downloading https://codeload.github.com/hnsl/unox/tar.gz/0.2.0
Already downloaded: /Users/fabiobrunelli/Library/Caches/Homebrew/unox-0.2.0.0
==> Downloading https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
Already downloaded: /Users/fabiobrunelli/Library/Caches/Homebrew/unox--homebrew-virtualenv-15.1.0.tar.gz
==> python2.7 -c import setuptools... --no-user-cfg install --prefix=/tmp/unox--homebrew-virtualenv-20180307-12325-142vvkl/target --single-version-externally-managed --record=installed.txt
==> python2.7 -s /tmp/unox--homebrew-virtualenv-20180307-12325-142vvkl/target/bin/virtualenv -p python2.7 /usr/local/Cellar/unox/0.2.0_1/libexec
==> Downloading https://pypi.python.org/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz
Already downloaded: /Users/fabiobrunelli/Library/Caches/Homebrew/unox--watchdog-0.8.3.tar.gz
==> /usr/local/Cellar/unox/0.2.0_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/unox--watchdog-20180307-12325-1je6u0i/watchdog-0.8.3
Last 15 lines from /Users/fabiobrunelli/Library/Logs/Homebrew/unox/03.pip:
Removing source in /private/tmp/pip-PjERgM-build
Command "/usr/local/Cellar/unox/0.2.0_1/libexec/bin/python -u -c "import setuptools, tokenize;file='/private/tmp/pip-PjERgM-build/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-6nCpUX-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/unox/0.2.0_1/libexec/include/site/python2.7/watchdog" failed with error code 1 in /private/tmp/pip-PjERgM-build/
Exception information:
Traceback (most recent call last):
File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
prefix=options.prefix_path,
File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
**kwargs
File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
spinner=spinner,
File "/usr/local/Cellar/unox/0.2.0_1/libexec/lib/python2.7/site-packages/pip/utils/init.py", line 707, in call_subprocess
% (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/unox/0.2.0_1/libexec/bin/python -u -c "import setuptools, tokenize;file='/private/tmp/pip-PjERgM-build/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-6nCpUX-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/unox/0.2.0_1/libexec/include/site/python2.7/watchdog" failed with error code 1 in /private/tmp/pip-PjERgM-build/

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/eugenmayer/homebrew-dockersync/issues`

Please may you help me?

**Comment by EugenMayer** [comment]
are you planning to use unison or the default native_osx strategy?

**Comment by EugenMayer** [comment]
Also maybe check https://github.com/EugenMayer/homebrew-dockersync/issues/1 .. i am honest, i will not really be able to invest time into this, so you might rather try and tackle this yourself if its any critical for you

**Comment by arioch1984** [comment]
Hi @EugenMayer , thank's for your reply!
Yes I am planning to use unison, actually I use it to sync files between my PC and a virtual machine (vagrant and virtual box).
Unfortunately I have to use polling strategy and if I could use file system triggers it would be more efficient.

**Comment by EugenMayer** [comment]
Well you are just using docker-sync for something totally different then it was designed too.

**Comment by arioch1984** [comment]
Hi @EugenMayer, sorry but I am not agree with you.
As you could read in my first post I only tried to install the brew package eugenmayer/dockersync/unox.
When I try to install I have the error I reported.
What in this behaviour is wrong?

**Comment by EugenMayer** [comment]
I see, so you are just trying to use the subpackage. Well unox is a beast, feel free to provide any PRs to fix its installation, it was very hard to get it done in the first place, i am not planning to do anything else in that regard anymore. You will most probably already noticed, there is not a single brew tap for unox out there - with a reason.

**Comment by arioch1984** [comment]
ok @EugenMayer, I think I had to try another solution :(

**Comment by EugenMayer** [comment]
you can also install unox the old fashioned way yourself https://github.com/hnsl/unox

**Comment by arioch1984** [comment]
Hi @EugenMayer, thanks for your reply.
Do you mean pip install procedure?
If yes unfortunately this procedure has the same result :(

**Comment by EugenMayer** [comment]
Then its time to fix your setup :)
